Concordium/concordium-contracts-common

- Cargo.toml
- src/impls.rs
- src/types.rs
Define a notion of policy that corresponds to the information accessible about the sender.
The design of the policy is such to require a minimal overhead when accessing. This makes it slightly awkward to access, but higher-level abstractions can be built that do not require the programmer to deal with low-level, incremental policy access.
In order to simplify some of the code and dependencies this PR also
- moves Init/Receive contexts out of the library. They are only needed by the node integration, hence they are moved there.
> Expose policy

- src/impls.rs
- src/schema.rs
- src/types.rs
Introduces transparent types for Timestamp and Duration, and extends the schema to include these.
> Add transparent types for timestamp and duration

- Cargo.toml
- src/impls.rs
- src/types.rs
Slot time can be used instead of block height and slot number for use-cases.
It is unclear how one would use the finalized height for anything meaningful.
> Remove values from chain context.

- CHANGELOG.md
- src/constants.rs
- src/impls.rs
- src/lib.rs
- src/schema.rs
- src/types.rs
Closes CB-1203.
Adds support for sending contract names and receive names as parameters.
Adds the schema types:
- `ContractName` 
- `ReceiveName`
Also adds the following data types:
- `ContractName`
- `OwnedContractName` (implements `SchemaType`)
- `ReceiveName`
- `OwnedReceiveName` (implements `SchemaType`)
The owned versions can be converted into their counterparts with `as_ref()`.
Related:
https://gitlab.com/Concordium/smart-contracts/-/merge_requests/125
https://gitlab.com/Concordium/concordium-client/-/merge_requests/291
https://github.com/Concordium/concordium-rust-smart-contracts/pull/25
> CB-1203: Contract and receive names

- src/impls.rs
After switching to use SizeLength::U16 we can no longer use the
serialization from String.
> Fix serialization of Contract- and ReceiveName

- Cargo.toml
- src/types.rs
Adding `fuzz` feature that allows the `wasm-chain-integration` repository to support fuzzing. For that, we derive `Debug` and `Arbitrary` for a bunch of data types.
> Features for fuzzing support

- CHANGELOG.md
- Cargo.toml
- src/constants.rs
- src/lib.rs
- src/types.rs
Contract and receive names were being validated with different functions. Now, I've combined them into one.
- Move `MAX_FUNC_NAME_SIZE` from wasm-transform, as wasm-transform now depends on this repo (separate PR)
- Make the validation functions public
- Add some additional error variants, as they were missing from `NewContractNameError` and `ReceiveNameError`
> Unique validation functions for contract and receive names

- src/schema.rs
- src/traits.rs
Add helper functions for serializing lengths of specific `size_lengths`.
Needed for https://github.com/Concordium/concordium-rust-smart-contracts/pull/39
- Add helper functions for serializing lengths of specific `size_lengths`.
> Add helpers for serializing lengths of specific sizes

- src/types.rs
Derive a `Debug` implementation for the `Address` type. It seems reasonable to have in all cases, not only for the "fuzz" feature, and it's consistent with the current `derive` for `ContractAddress` and `AccountAddress`.
Added `Debug` to the list of derived trait implementations. Since it's derived unconditionally, we can remove it from the list for the "fuzz" feature.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf
> Add derive Debug for the Address type

- .github/workflows/linter.yml
- CHANGELOG.md
- src/types.rs
As part of new clippy lints an inefficiency in the way receive and contract names
were handled was discovered. Changing the type of the methods is technically a
breaking API change. However since these are methods on a type that is Copy, the
impact is going to be negligible. Hence the decision to remove the needless indirection.
Support rust 1.53.
- Remove the needless reference in `to_owned` and `get_chain_name` methods.
> Update rust to 1.53.

- src/impls.rs
Reduce code size. On a trivial contract example that only checks that the sender is an account this reduces code size from 9.7kB to 500B. The reason is that the allocator is not included when these functions are inlined.
Add some inline annotations.
> Add inline annotations to reduce generated code size.

- CHANGELOG.md
- Cargo.toml
- src/impls.rs
- src/schema.rs
- src/types.rs
Support using `Address` in a `BTreeMap` and contract schemas.
Types implement Hash and add support for hashmaps in `no-std`.
- Derive `PartialOrd` and `Ord` for `ContractAddress` and `Address`.
- Implement `SchemaType` for `Address`.
- Add `HashMap` and `HashSet` from the `hashbrown` crate to support `no-std`.
- Make `HashMap` and `HashSet` default to the `fnv` hasher.
- Derive `Hash` for `Amount`, `Timestamp`, `Duration`, `AccountAddress`, `ContractAddress`, `Address`, `ContractName`, `OwnedContractName`, `ReceiveName` and `OwnedReceiveName`.
> Adding better support for hashmaps

- CHANGELOG.md
- src/impls.rs
- src/schema.rs
Avoid macro generated implementations for array by using const generics.
- Replace macro generated implementations up to 32 of Serial and Deserial for `[T, x]` with one using const generics.
- Replace macro generated implementations up to 32 of SchemaType for `[T, x]` with one using const generics.
> Use const generics for impl Serial and Deserial for arrays

- src/types.rs
Remove unused code.
In the past heights and slots were directly accessible via the contract context, but this has been removed some time ago.
Leaving these values in only causes confusion.
> Remove unused and misleading types.

- CHANGELOG.md
- Cargo.toml
- src/impls.rs
- src/schema.rs
- src/types.rs
As title states, this serves to update references to the token to match the token name.
- Rename occurrences of GTU to CCD
- Bump major version due to changes to public API 
> Rename references to GTU to CCD.

- CHANGELOG.md
- src/impls.rs
- src/types.rs
Introduce types for parameters and entrypoints.
Introduce new types for entrypoints and parameters. The latter is useful to have a central place for its serialization.
> Introduce types for parameters and entrypoints.

- src/types.rs
Adds an auto-serializing constructor for `OwnedParameter` similar to what we had with the `send` helper function.
Add two constructors to `OwnedParameter`
> Auto-serializing constructor for `OwnedParameter`

- CHANGELOG.md
- Cargo.toml
- src/impls.rs
- src/schema.rs
- src/traits.rs
- src/types.rs
Minor helpers and instances that are needed in cargo-concordium.
The main change is moving some methods from OwnedReceiveName to ReceiveName since they are sometimes needed there, and since it is cheap to convert to the latter from the former, 
> Add a few helper instances related to receive/entrypoint names.

- src/impls.rs
Closes #31.
Directly serialize the byte array.
> Remove the intermediate vector allocation when serializing strings.

- CHANGELOG.md
- Cargo.toml
- src/schema.rs
Support LEB128 signed and unsigned integers and bytes in the contract schema.
- Extended the contract schema with ULeb128, ILeb128, ByteList and ByteArray.
> Add Leb128 integers and bytes to the contract schema

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/Cargo.toml
- concordium-contracts-common/src/types.rs
Builds on top of https://github.com/Concordium/concordium-contracts-common/pull/46.
Closes https://github.com/Concordium/concordium-contracts-common/issues/43.
- Implement `std::error::Error` when the `std` feature is enabled
When compared to https://github.com/Concordium/concordium-contracts-common/pull/46: none of the examples change in size.
> Implement error for error types

- concordium-contracts-common-derive/Cargo.toml
- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/schema.rs
- concordium-contracts-common/src/types.rs
Related to https://github.com/Concordium/concordium-base/issues/180
- Match serde implementation with the Rust SDK for `Address`.
- Export `AccountAddressParseError` when `derive-serde` is enabled.
- Add amount unit tests found in base.
- Add `micro_ccd` getter for `Amount`.
Notice the `From<u64> for Amount` was not introduced from base, as the behavior of this might not be obvious.
Instead, the functions `Amount::from_micro_ccd` or `Amount::from_ccd` should be used instead.
> Unify common types from Rust SDK and crypto_common

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/impls.rs
- concordium-contracts-common/src/traits.rs
Add a `cursor_position` method to the `Seek` trait. It was needed for https://github.com/Concordium/concordium-rust-smart-contracts/pull/141.
- Add `cursor_position` method and implement it for `Cursor`
> Add `cursor_position` method to `Seek`

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/schema.rs
Adds a v2 schema, which supports schemas for errors.
Part of the solution for https://github.com/Concordium/concordium-rust-smart-contracts/issues/155
- Rename some types by adding a `V1` suffix.
- Adding some schema `V2` types and implementing serialization and helpers.
- [x ] I have documented my code, in particular the intent of the
> Add v2 contract schemas

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/impls.rs
- concordium-contracts-common/src/schema.rs
- concordium-contracts-common/src/types.rs
- Add type representing a module reference.
- Implement `SchemaType` for `OwnedEntrypointName`.
> Add type for ModuleReference

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/types.rs
Make `Duration::from_*` functions constant, so they can be used to create `Duration` instances at compile-time. This would safe some computations in smart contracts using static time constraints.
> Make `Duration::from`  functions constant

- concordium-contracts-common/Cargo.toml
- concordium-contracts-common/src/schema.rs
- concordium-contracts-common/src/types.rs
Replace the `base58check` crate with the `bs58` crate.
It is better designed and maintained, and has up-to-date dependencies.
Closes https://github.com/Concordium/concordium-contracts-common/issues/60
> Use bs58 instead of base58check.

- concordium-contracts-common/src/impls.rs
- concordium-contracts-common/src/types.rs
Do not use functions deprecated in chrono 0.4.23
Replace usage of deprecated functions with suggested alternatives.
> Support chrono 4.23.

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/schema_json.rs
The current implementation serializes enum variant indices using u32 instead of u16.
Change type of output.
> Bug in enum deserialization.

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/schema_json.rs
The write_bytes_to_json should have been a method.
Make it more ergonomic to serialize JSON values according to the schema.
Add helper methods that are more discoverable, and simpler to use.
> Make the serialization of JSON values according to the schema more ergonomic

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/Cargo.toml
- concordium-contracts-common/src/schema_json.rs
It should output a contract address in the format that is used in JSON everywhere else. Not as a string.
Fixes a bug that makes it so that to_json output cannot be parsed back.
Use the correct to_json instance.
> Fix schema's to_json for contract addresses.

- concordium-contracts-common/src/types.rs
Arbitrary for attribute value is needed for fuzzing.
> Add arbitrary instance for AttributeValue for use in fuzzing.

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/constants.rs
- concordium-contracts-common/src/hashes.rs
- concordium-contracts-common/src/impls.rs
- concordium-contracts-common/src/lib.rs
- concordium-contracts-common/src/types.rs
For legacy reasons, we have two pairs of types that are nearly identical.
Namely, the `Parameter` from concordium-base (not to be confused by the borrowing `Parameter` from this repo) and `OwnedParameter` from this repo.
And `ModuleRef` from concordium-base and `ModuleReference` from this repo.
This pull request addresses that issue.
Closes #74 
- Unify the parameter types
- Try to match the old API to avoid breaking changes. See changelog for details.
- Unify the module reference types:
- Move the `HashBytes` type from base to here and use it for the `ModuleReference`.
- Try to match the old API to avoid breaking changes. See changelog for details.
> Unify parameter and module reference types

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/types.rs
Replace `new` with `from_serial` which also checks the length.
- Rename `new` to `from_serial` which ensures valid length
- Also add empty methods to both versions of parameter
- And implement Default for parameter
> Rename `new` to `from_serial` which ensures valid length

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/schema_json.rs
This PR fixes schema JSON deserealization of signed numbers.
`.as_u64()` was used to parse signed numbers, which caused a failure when supplied with a negative value. This was replaced by `.as_i64()`.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf
> Fix schema JSON deserialization of signed integers

- concordium-contracts-common/src/types.rs
Marking `new_unchecked` as constant in EntrypointName.
This change is needed for the `supportsPermit` MR:
https://github.com/Concordium/concordium-rust-smart-contracts/pull/234
> Change new_unchecked as constant in EntrypointName

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/types.rs
Allow writing
```
assert_eq!(foo.receive_name, "foo.bar")
```
in particular in the integration testing library.
> Allow comparing different names to str directly for improved ergonomics.

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/impls.rs
Fixes https://github.com/Concordium/concordium-rust-smart-contracts/issues/242
In particular this allows using TokenIdVec as map keys.
> Remove Copy requirement.

- .github/workflows/linter.yml
- README.md
- concordium-contracts-common-derive/CHANGELOG.md
- concordium-contracts-common-derive/Cargo.toml
- concordium-contracts-common-derive/src/lib.rs
- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/Cargo.toml
- concordium-contracts-common/src/hashes.rs
- concordium-contracts-common/src/types.rs
A number of small changes needed for the integration testing library.
- Add the method
- The newest version of `rust-decimal` requires rust 1.60, so the rust version is also updated.
- Update the Rust edition to `2021`
- Used `cargo fix --edition` to put spaces in the macros.
- Update rust version in CI 
- Add contributor section in README which also explains the nightly version needed for `cargo fmt`
- Remove the SDK feature
> Remove `sdk` feature, update version and edition, add helper function

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/src/types.rs
Implement `serde` for `Duration`.
Related to https://github.com/Concordium/concordium-base/pull/372 and https://github.com/Concordium/concordium-rust-sdk/pull/92
> Implement serde for Duration using FromStr and Display

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/Cargo.toml
- concordium-contracts-common/src/schema_json.rs
- concordium-contracts-common/src/types.rs
Adds trace information for errors happening when (de)serializing using contract schemas. I added a few unit tests, mostly to test the format of the trace errors for both `JsonError` and `ToJsonError` are as expected, however they are nowhere exhaustive (If we need more, let me know).
- Adds `JsonError::TraceError`, which holds information about the path to the original `JsonError` produced when serializing from schema type
- Adds `ToJsonError` type, which is now the error type returned when deserializing to schema type.
> Improve serialization errors

- .github/workflows/linter.yml
- README.md
- concordium-contracts-common-derive/CHANGELOG.md
- concordium-contracts-common-derive/Cargo.toml
- concordium-contracts-common-derive/src/attribute.rs
- concordium-contracts-common-derive/src/derive.rs
- concordium-contracts-common-derive/src/lib.rs
- concordium-contracts-common-derive/src/smart_contract.rs
- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/Cargo.toml
- concordium-contracts-common/src/lib.rs
Remove duplication code by merging `concordium-std-derive` into `concordium-contracts-common-derive`.
Related to https://github.com/Concordium/concordium-rust-smart-contracts/issues/290.
Should be merged before https://github.com/Concordium/concordium-rust-smart-contracts/pull/291.
- Move macros from `concordium-std-derive` to `concordium-contracts-common-derive`. 
- Copied functions `is_valid_contract_name` and `is_valid_receive_name` from `concordium-contracts-common` to avoid the dependency in the macro.
- Add `smart-contract` feature to `concordium-contracts-common`, which enables the macros only relevant in a smart contract.
- Restructure code in `concordium-contracts-common-derive` by moving the logic of the derive macros and attribute macros into separate modules. …
> Add macros from concordium-std-derive

- .github/workflows/linter.yml
- concordium-contracts-common-derive/CHANGELOG.md
- concordium-contracts-common-derive/src/derive.rs
- concordium-contracts-common-derive/src/lib.rs
Related to https://github.com/Concordium/concordium-rust-smart-contracts/issues/283.
Tests are implemented in https://github.com/Concordium/concordium-rust-smart-contracts/pull/293.
- Deriving `Serial`, `Deserial`, `DeserialWithState` and `SchemaType` now produces an implementation which adds a bound to each of the type parameters to implement the relevant trait.
Note that `Serial` and `DeserialWithState` skips this bound for `state_parameter` when/if this is provided. This is not the behavior of `Deserial` and `SchemaType` since they are incompatible with `DeserialWithState` and therefore `state_parameter` is never present in these cases.
- Deriving `SchemaType` will now produce code even without the `build-schema` feature being enabled. This PR depends on it to avoid having to introduce …
> Bound for type parameters

- concordium-contracts-common-derive/CHANGELOG.md
- concordium-contracts-common-derive/src/derive.rs
Fix error when users provide an invalid field attribute.
Currently, when deriving `Deserial` or `DeserialWithState` for a struct with an invalid field attribute such `#[concordium(size_length = "2")]`, where this is expected to be a number literal.
Expected:
Actual:
> Produce proper error for field attributes when deriving Deserial

- concordium-contracts-common-derive/CHANGELOG.md
- concordium-contracts-common-derive/src/derive.rs
- concordium-contracts-common-derive/src/lib.rs
Related to https://github.com/Concordium/concordium-rust-smart-contracts/issues/299
Should be merged before https://github.com/Concordium/concordium-rust-smart-contracts/pull/301.
- Support variant attribute `tag` and container attribute `repr`.
- Add `ensure` and `bail` macros internally to increase readability (similar to the ones from `anyhow`).
> Add `tag` and `repr` attribute for deriving serialization

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/Cargo.toml
- concordium-contracts-common/src/schema.rs
Needed this for the custom indexer epic, thought it could be useful elsewhere as well.
- Add `from_base64_str` to `VersionedModuleSchema`
> Adds function to parse VersionedModuleSchema from base64

- concordium-contracts-common-derive/Cargo.toml
- concordium-contracts-common-derive/src/attribute.rs
- concordium-contracts-common-derive/src/derive.rs
- concordium-contracts-common/Cargo.toml
- concordium-contracts-common/src/types.rs
A new version of the syn crate has been released with better support for the Rust syntax and a number of helpers that we would want.
This PR updates the dependency and migrates our code. Not changes for the user.
Should be merged with https://github.com/Concordium/concordium-base/pull/402
> Update syn to version 2 for derive crate

- concordium-contracts-common-derive/CHANGELOG.md
- concordium-contracts-common-derive/src/derive.rs
- concordium-contracts-common-derive/src/lib.rs
- concordium-contracts-common/src/impls.rs
- concordium-contracts-common/src/types.rs
Related to https://github.com/Concordium/concordium-rust-smart-contracts/issues/307.
Support `forward` attribute in derive macros for `Serial`, `Deserial`, `DeserialWithState` and `SchemaType`.
Should be merged before https://github.com/Concordium/concordium-rust-smart-contracts/pull/314
> Derive forward attribute

- concordium-contracts-common/CHANGELOG.md
- concordium-contracts-common/Cargo.toml
- concordium-contracts-common/src/impls.rs
- concordium-contracts-common/src/lib.rs
- concordium-contracts-common/src/types.rs
Signature and key types are not solely used by smart contracts anymore. It makes sense to move them to `concordium-contracts-common` from `concordium-std` so they are easier accessible and can be imported by e.g. backends to construct input parameters.
Add signature and key types to `concordium-contracts-common`
> Add signature and key types to concordium-contracts-common

- concordium-contracts-common-derive/CHANGELOG.md
- concordium-contracts-common-derive/src/derive.rs
- concordium-contracts-common-derive/src/lib.rs
Complementary to https://github.com/Concordium/concordium-rust-smart-contracts/pull/321, which now removes `StateClone` trait completely
* Remove `derive(StateClone)` proc macro, as it's not needed anymore
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf
> Remove `derive(StateClone)` completely

- README.md
Replace readme with a deprecation notice of the repo and redirect users to the new location of the libraries.
- Replace readme
- Handle open issues (closed one, moved one to base)
- Handle open pull requests
> Add deprecation notice of repository (not library) to README
